name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run additional command
      run: |
        docker run --rm -v -v ${{ github.workspace }}:/tmp/repo my-image-name:$(date +%s) sh -c 'python -m assemblyline_v4_service.dev.run_service_once suricata_.suricata_.Suricata /tmp/repo/test/*.pcap'